### ISSUE TITLE
User level documentation

### ISSUE THREAD

**Issue by owainlewis** [kubernetes-client/haskell#10]
Add some simple request (list Pods etc) examples to the README to help new users get started and how to authenticate etc.

**Comment by guoshimin** [comment]
I'll try to add some documentation, probably just replace the autogenerated kubernetes/README.md, which is not that useful for the user.

**Comment by guoshimin** [comment]
@owainlewis We need a Haskell reviewer. Would you be up for reviewing #12 ?
