### ISSUE TITLE
Put on Hackage

### ISSUE THREAD

**Issue by mjhopkins** [kubernetes-client/haskell#23]
Hi,

Is there a plan to put this code up on Hackage?

Even if you don't think you're ready for a major release, having the code deployed to Hackage would be really helpful for a lot of people.

**Comment by ghuntley** [comment]
Agreed. I'd like to help (as a maintainer) with this project let me know if you need help/I'm @ghuntley on slack say howdy.

**Comment by dservgun** [comment]
Welcome to the team.
 I was implementing the exec call and am sure my Pr needs review . Can we setup please a time so we can push this through.
Thanks 
Dinkar

**Comment by guoshimin** [comment]
@ghuntley Thanks for volunteering! This project definitely needs all the help it can get. If you are up for it, can you take https://github.com/kubernetes-client/haskell/issues/5?

**Comment by akshaymankar** [comment]
Hello, I see this issue is stuck since more than a year. What is stopping this?

**Comment by guoshimin** [comment]
At this point there is no blocker. Just needs someone to do it...

**Comment by akshaymankar** [comment]
Ok, I will do it if it is okay. Please let me know who all should be added to the maintainer group.

**Comment by guoshimin** [comment]
You can add me, @jonschoning , and @jkachmar. What do you need besides names?

**Comment by guoshimin** [comment]
and yourself, of course, if you wish, but I think that's automatic when you upload a package?

**Comment by akshaymankar** [comment]
I actually need hackage usernames.

**Comment by guoshimin** [comment]
I created an account. The username is guoshimin.

**Comment by akshaymankar** [comment]
I uploaded the core package here: https://hackage.haskell.org/package/kubernetes-client-core-0.1.0.0
But the build is failing because stack is generating old version bounds, it is using lts-10.
I can see the latest openapi-generator uses lts-13.5. I will bump it and send PRs to the gen repo and this repo.

Also, @guoshimin I have added you as a maintainer on hackage.

**Comment by akshaymankar** [comment]
Sorry, I was wrong. The generated code already is using lts-13.9, the stack.yaml outside the project which I used to generate sdist is using lts-10. I will update it and send a PR.

**Comment by guoshimin** [comment]
Thanks for pushing on this. I'm a little confused. I was under the
impression that hackage doesn't use stack.

**Comment by akshaymankar** [comment]
Hackage doesn't use stack, this is true. But we can generate packages to be uploaded to hackage using stack like this: `stack sdist --pvp-bounds both`. Which is how I generated the package.

**Comment by akshaymankar** [comment]
The core package is uploaded to hackage and it works 🎉 
See it here: https://hackage.haskell.org/package/kubernetes-client-core-0.1.0.1

I think we should tag the commit on which the version was built, which is this: 24171f73b86623adaffb586093ac288f97fab1c3. @guoshimin can you please do that? 
For tagging we'll have to remember that we have two artifacts (core and client package) and their versions will likely diverge, so we should have tagging scheme accordingly.

I am working on client package now and I hope I get it right the first time 🤞

**Comment by guoshimin** [comment]
I don't think I have permissions to push tags. I'm not sure how this is done. @brendandburns Can you chime in?

**Comment by akshaymankar** [comment]
I have uploaded kubernetes-core-0.1.0.0 to hackage: https://hackage.haskell.org/package/kubernetes-client-0.1.0.0

Hackage will run its build in a bit and we'll know if it is good.

I needed to make some changes to make sure latest versions of all dependencies were usable and also to make sure oldest known versions of dependencies are persisted long term. I have created this PR for it: #49

**Comment by akshaymankar** [comment]
I also realized that I did not have to upload another version of `kubernetes-client-core` to update the bounds. I could've just edited the package and hackage would've created another revision. But I guess its too late to do anything 😞

**Comment by akshaymankar** [comment]
Alright, so both packages are on hackage 🎉 
Me and @guoshimin are the maintainers on hackage as of now.

Next, I was going to try to add them to stackage-nightly, but unfortunately kubernetes-client-core is going to need more lenient upper bounds: http://packdeps.haskellers.com/feed?needle=kubernetes-client-core. I think we'll have to fix it in openapi-generator. 

But as the goal of this issue was to get it on hackage, I think we can close this one and create another one for stackage.

**Comment by guoshimin** [comment]
Awesome! Huge thanks for pushing it through.

Any ideas why the https://hackage.haskell.org/package/kubernetes-client page is not showing the README?

And why does it show only me as the maintainer? Is it from package.yaml?

**Comment by akshaymankar** [comment]
> Any ideas why the https://hackage.haskell.org/package/kubernetes-client page is not showing the README?

Good catch, this is because `package.yaml` doesn't have `README.md` in `extra-source-files`. Unfortunately it cannot be fixed in a revision. I will upload another version quickly and send a PR for that.

> And why does it show only me as the maintainer? Is it from package.yaml?

Yes, this is from package.yaml, I will add myself and send a PR.
I think I can update the `kubernetes-client-core` cabal file, so that won't require a new version.

**Comment by guoshimin** [comment]
Thanks for taking care of this. Can you remove my email address from it
while you are at it?

**Comment by akshaymankar** [comment]
So, you want only your name in it?

**Comment by akshaymankar** [comment]
Also, can you verify if this candidate looks ok: https://hackage.haskell.org/package/kubernetes-client-0.1.0.1/candidate

**Comment by guoshimin** [comment]
What's the prevailing practice for including email addresses? I spot
checked a few packages and the results are varied. Seems most include the
email addresses. So I'm fine with including mine.

The page looks good.

**Comment by akshaymankar** [comment]
Ok, I added your email address back and published it. I have also added myself to `maintainers` in the core package. #50 has the commits for this and addition of README.
