### ISSUE TITLE
Logging framework selection

### ISSUE THREAD

**Issue by jkachmar** [kubernetes-client/haskell#32]
Currently the `haskell-http-client` OpenAPI generator selects one of `katip` or `monad-logger` when generating the client functions.

Perhaps this is too much additional complexity, but it seems like it wouldn't be _too_ much extra effort for the upstream `haskell-http-client` to generate both `{{baseModule}}.Logging.MonadLogger` and `{{baseModule}}.Logging.Katip`, make `{{baseModule}}.Logging` a re-export of one of the two (based on some CPP directive), and add a flag to the `cabal` file that toggles the CPP directive and selects `other-modules`/`exposed-modules`.

---

I'm opening the issue to this tracket simply because this is the most active consumer of the `haskell-http-client` generator that I'm aware of, so I imagine peoples' opinions here would be the most informed.

**Comment by jkachmar** [comment]
cc @jonschoning

**Comment by jonschoning** [comment]
I think that's doable. 

I was also thinking about removing `katip` completely, but I could also just make `monad-logger` the default option in the above scenario.

**Comment by jonschoning** [comment]
https://github.com/OpenAPITools/openapi-generator/pull/2258

**Comment by jkachmar** [comment]
This looks like it's been addressed, but I'll leave the issue open until we've merged the changes introduced by kubernetes-client/gen#108 that gives us access to this.
