### ISSUE TITLE
Integration test on travis

### ISSUE THREAD

**Issue by guoshimin** [kubernetes-client/haskell#40]
https://blog.travis-ci.com/2017-10-26-running-kubernetes-on-travis-ci-with-minikube

**Comment by jkachmar** [comment]
It might also be worth considering Kubernetes in Docker (`KinD`), as shown here: https://github.com/xmudrii/travis-kind/blob/master/.travis.yml

**Comment by guoshimin** [comment]
Neat!

**Comment by akshaymankar** [comment]
I tried using kind, it starts within 2 minutes on travis!
I really like the way csharp client has integration tests. There are examples which are just executed as integration tests. I am thinking of doing the same. Please let me know if anybody has opinions on this.

I am also assuming that nobody is working on this, if somebody is please shout at me :)

**Comment by akshaymankar** [comment]
/remove-lifecycle stale

 guess why we didn't get travis will always be a mystery. 

I tried compiling the project in prow on kind, but it failed on my macbook while consuming 400% CPU for 2 hour straight. I will try it again on a linux machine soon. But I think it would be a PR to the [test-infra repository](https://github.com/kubernetes/test-infra) anyways.

So, I think we should merge this PR as it anyways has examples which might be helpful to new users and the travis config can also be used by the forks while developing new things.

WDYT @guoshimin?
