### ISSUE TITLE
Packaging

### ISSUE THREAD

**Issue by mbohlool** [kubernetes-client/haskell#5]
Configure and package the client (Cabal?).

**Comment by alexjg** [comment]
I'm interested in helping with this. What exactly needs doing? Just getting all the necessary config in place to upload to hackage?

**Comment by guoshimin** [comment]
Yeah, pretty much.

**Comment by alexjg** [comment]
I'm still interested in this and I think it's pretty important. I don't think it should be closed.

**Comment by guoshimin** [comment]
This is same as #23 
/close
