### ISSUE TITLE
Should we make a release?

### ISSUE THREAD

**Issue by akshaymankar** [kubernetes-client/haskell#62]
A few PRs have been merged since the last (first!) release. I think we should make another one now. 
With #60 and #51, we've changed the APIs significantly to make us bump major according to PVP.
Also, with #60 all the dependencies are on stackage, so we can also add both the packages to stackage.

**Comment by guoshimin** [comment]
👍

**Comment by amarrella** [comment]
Hi :) Thanks for this project! Any news on a possible release?

**Comment by jonschoning** [comment]
👍

**Comment by erthalion** [comment]
Hi,

I also would love to ask about the next release. At the moment there are two of
them on hackage (0.1.0.0, 0.1.0.1), but apparently they don't include the
latest changes, which are already reflected e.g. in the readme, and it's a bit
confusing.

**Comment by akshaymankar** [comment]
Hey @erthalion, Thanks for the nudge. I will take some time to upload a release by this weekend.

**Comment by akshaymankar** [comment]
Hello everyone, I made a release for both packages. They are both versioned 0.2.0.0. You can look at them on hackage at:
- [kubernetes-client-core](https://hackage.haskell.org/package/kubernetes-client-core-0.2.0.0)
- [kubernetes-client](https://hackage.haskell.org/package/kubernetes-client-0.2.0.0)

I wasn't able to find time in past few months, mostly because I lost motivation after our CI stuff got stuck in foundation bureaucracy. I will try again to get it unstuck and then hopefully we can work on improving this project.

For now, I will close this issue and create another one if I think we need a release to seek opinions. Please feel free to create a similar issue if you think a new release makes sense.

/close
