### ISSUE TITLE
Proposal: Default to openssl

### ISSUE THREAD

**Issue by akshaymankar** [kubernetes-client/haskell#63]
I saw [this thread on twitter](https://twitter.com/ProgrammerDude/status/1183747024509902849) and realized that the `mkKubeClientConfig` defaults to using the native tls client and provides no _easy_ way of overriding it.

So, I propose we should just use `http-client-openssl` instead of `http-client-tls` for creating the client.

**Comment by guoshimin** [comment]
👍 

Didn't know `http-client-openssl` existed.
