### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by cirquit** [kubernetes-client/haskell#65]
It would be awesome to have some simple examples, similar to the [official python examples](https://github.com/kubernetes-client/python/tree/master/examples).

In my case some useful ones would be "create deployment from file" and "reconfigure a live replicaset".

If I manage to get some up and running, would you be open to a pull request? Otherwise, what is the best source to learn about the API?

It seems slightly overkill to read the automatically generated hackage docs.

**Comment by cirquit** [comment]
So after setting up the environment #64 it seems like I can't get the basic functionality to start working with the library. It seems like any functionality from `http-client` is hidden and I can't access it the usual way.

Example:
```haskell
> (manager, config) <- connectKubernetes
> (MimeResult response status) <- dispatchMime manager config $ CoreV1.listNamespace $ Accept MimeJSON
> responseStatus status
<interactive>:32:1: error:
    Variable not in scope:
      responseStatus
        :: http-client-0.5.14:Network.HTTP.Client.Types.Response
             bytestring-0.10.8.2:Data.ByteString.Lazy.Internal.ByteString
           -> t
``` 

Per this [cabal FAQ](https://www.haskell.org/cabal/FAQ.html#hidden-packages-b) it seems the proposed solution was to add `http-client` into the `package.yaml`, but it did not help at all.

Maybe it's some easy solution I'm missing because it's been some time since working with Haskell.

**Comment by akshaymankar** [comment]
I have written couple of examples in #61. Hopefully we'll grow them soon, we can use this issue to track that.


> It seems like any functionality from http-client is hidden and I can't access it the usual way.

Cabal treats all transitive dependencies as hidden packages, so you cannot import things from them. To import them, you'd have to add them as a direct dependencies of your package. In this case, add `http-client`to `package.yaml` and `import Network.HTTP.Client`

**Comment by cirquit** [comment]
Thank you for the examples, seems like I can get started with those. For the hidden package problem - this is exactly what I've done and it still is not possible for me to import the module:

```haskell
> stack ghci
Main KubernetesWrapper> import Network.HTTP.Client.Types
<no location info>: error:
    Could not load module ‘Network.HTTP.Client.Types’
    it is a hidden module in the package ‘http-client-0.5.14’
```

I've already tried `stack clean`, deleting the project and setting it up again and specifying the version to `http-client-0.5.14` in the `package.yaml` under dependencies.
