### ISSUE TITLE
Wrong return type in deleteNamespacedPersistentVolumeClaim

### ISSUE THREAD

**Issue by thomasjm** [kubernetes-client/haskell#86]
https://github.com/kubernetes-client/haskell/blob/b078aa6fe0f97cf6b52eaac0cd40082b67b0e8bd/kubernetes/lib/Kubernetes/OpenAPI/API/CoreV1.hs#L3810-L3816

In the type above, the return value says `V1Status`. I think it should be `V1PersistentVolumeClaim`; see the docs here:

https://kubernetes.io/docs/reference/kubernetes-api/config-and-storage-resources/persistent-volume-claim-v1/#response-9

I noticed this because of a parsing error when running this command against my cluster. I'm not sure the right place to fix it. The `swagger.json` file in this repo also lists the return type as `#/definitions/v1.Status`.

**Comment by jonschoning** [comment]
unfortunately the swagger.json at https://raw.githubusercontent.com/kubernetes/kubernetes/release-1.16/api/openapi-spec/swagger.json shows that the response is
```
    "/api/v1/namespaces/{namespace}/persistentvolumeclaims": {
      "delete": {
...
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/io.k8s.apimachinery.pkg.apis.meta.v1.Status"
            }
          },
```

**Comment by jonschoning** [comment]
The `settings` file currently targets kubernetes 1.16 and it looks like the api changed in 1.18 to return a `V1PersistentVolumeClaim`.

updating the targeted version in `settings` to >= 1.18 and re-gen client should work.

**Comment by thomasjm** [comment]
Ah, thanks for researching that.

I was just reading about the [version skew policy](https://kubernetes.io/docs/setup/release/version-skew-policy/) and the policies of some major cloud providers. It seems each minor version is supported for about 3 years, so 1.16 is pretty much out of its support window now. What do you think of regenerating this library at 1.20? (What would be really cool is creating several tagged releases of this library at 1.16, 1.17 etc. so the user can choose.)

**Comment by jonschoning** [comment]
i think it's overdue for an update; i'll make a PR if everything goes well

**Comment by jonschoning** [comment]
c.f. https://github.com/kubernetes-client/haskell/pull/87
