### ISSUE TITLE
ssl error when specify master address as IP address in config file

### ISSUE THREAD

**Issue by fwt11** [kubernetes-client/haskell#90]
When i connect to the cluster using a kubeconfig file, I get a SSL error saying "name mismatch".

Is it possbile to change the signature of function `mkKubeClientConfig` from 
  `OIDCCache -> KubeConfigSource -> IO (NH.Manager, K.KubernetesClientConfig)` to `mkKubeClientConfig
  :: OIDCCache -> KubeConfigSource -> (TLS.ClientParams -> TLS.ClientParams)-> IO (NH.Manager, K.KubernetesClientConfig)`,
so I could pass `disableServerCertValidation` to it?

**Comment by JensGM** [comment]
This is pretty breaking. Was hoping to make use of this for some automation than lends it self neatly to Haskell, but we'll have to use python for now.

**Comment by robwithhair** [comment]
Is it possible to supply a domain to work around this error or is this project broken?  I have a member of my team working with this project as a dependency at the moment, so will post if able to reproduce the issue.

**Comment by JensGM** [comment]
If you use a domain and you control the config file your self, it's not an issue. We can't really control it since we're using GitHub actions to authenticate. It does work with domain names
